//
//  EventDetailInteractor.swift
//  NearbyEvents
//
//  Created by Ezra Berch on 1/1/19.
//  Copyright (c) 2019 Ezra Berch. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EventDetailBusinessLogic
{
    func doSomething(request: EventDetail.Something.Request)
    var event: Event? { get set }
}

protocol EventDetailDataStore
{
    var event: Event? { get set }
}

class EventDetailInteractor: EventDetailBusinessLogic, EventDetailDataStore
{
    var event: Event?
    
    var presenter: EventDetailPresentationLogic?
    var worker: EventDetailWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: EventDetail.Something.Request)
    {
        worker = EventDetailWorker()
        worker?.doSomeWork()
        
        let response = EventDetail.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
