//
//  MapModels.swift
//  NearbyEvents
//
//  Created by Ezra Berch on 12/31/18.
//  Copyright (c) 2018 Ezra Berch. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

enum Map
{
    // MARK: Use cases
    
    enum ConfigureMap
    {
        struct Request
        {
        }
        struct Response
        {
            var latitude: Double
            var longitude: Double
        }
        struct ViewModel
        {
            var region: MKCoordinateRegion
        }
    }
    
    enum GetEvents
    {
        struct Request
        {
            var latitude: Double
            var longitude: Double
            var miles: Int
            var search: String?
        }
        struct Response
        {
            var events: [Event]?
            var error: Bool
        }
        struct ViewModel
        {
            var events: [Event]?
            var error: Bool
        }
    }
    
    
    
}
